FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY vite.config.js ./
COPY index.html ./
COPY src ./src

RUN npm run build

FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
# expose SDK bundle as /checkout.js
COPY checkout.js /usr/share/nginx/html/checkout.js

EXPOSE 80
